### ISSUE TITLE
[13] Community hr_attendance_report_theoretical_time issue

### ISSUE THREAD

**Issue by sergioeix** [OCA/hr#1006]
Steps to reproduce:
1 set a public holyday calendar with at least 1 fixed day public holiday
2 aprrove leave period of the employe that matches this day
3 try to open the theoretical report view including this employe

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1339, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo13/odoo-custom-addons/hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report.py", line 234, in read_group
    record.employee_id.sudo(), record.date
  File "/opt/odoo13/odoo-custom-addons/hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report.py", line 193, in _theoretical_hours
    ("holiday_id.holiday_status_id.include_in_theoretical", "=", False),
  File "/opt/odoo13/odoo/addons/resource/models/resource_mixin.py", line 64, in _get_work_days_data
    domain=domain
  File "/opt/odoo13/odoo/addons/resource/models/resource_mixin.py", line 95, in _get_work_days_data_batch
    intervals = calendar._work_intervals_batch(from_datetime, to_datetime, calendar_resources, domain)
  File "/opt/odoo13/odoo/addons/resource/models/resource.py", line 486, in _work_intervals_batch
    leave_intervals = self._leave_intervals_batch(start_dt, end_dt, resources, domain, tz=tz)
  File "/opt/odoo13/odoo-custom-addons/hr_holidays_public/models/resource_calendar.py", line 82, in _leave_intervals_batch
    res[key] = res[key] | public_holidays
  File "/opt/odoo13/odoo/addons/resource/models/resource.py", line 102, in __or__
    return Intervals(chain(self._items, other._items))
  File "/opt/odoo13/odoo/addons/resource/models/resource.py", line 78, in __init__
    for value, flag, recs in sorted(_boundaries(intervals, 'start', 'stop')):
TypeError: '<' not supported between instances of 'hr.holidays.public.line' and 'resource.calendar.leaves'

**Comment by pedrobaeza** [comment]
This is due to an outdated `hr_holidays_public` source code.

**Comment by sergioeix** [comment]
ty Pedro
