### ISSUE TITLE
Attendance throws error "Invalid field 'birth_name' on model 'hr.employee.public'"

### ISSUE THREAD

**Issue by siarmiel** [OCA/hr#1203]
I installed some HR modules and birth-name seams to have a problem with attendance.

## Module

hr_employee_birth_name

## Describe the bug
When the module hr_employee_birth_name is installed, the attendance dialog failed on some users (maybe the rights are a problem). 

Error message:
Traceback (most recent call last):
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/api.py", line 886, in get
    return field_cache[record._ids[0]]
KeyError: 5
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/fields.py", line 1061, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/api.py", line 889, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'hr.employee(5,).user_id'
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/addons/web/controllers/main.py", line 1342, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/addons/hr_attendance/models/hr_employee.py", line 146, in attendance_manual
    can_check_without_pin = attendance_user_and_no_pin or (self.user_id == self.env.user and entered_pin is None)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/fields.py", line 2611, in __get__
    return super().__get__(records, owner)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/fields.py", line 1087, in __get__
    recs._fetch_field(self)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/models.py", line 3276, in _fetch_field
    self._read(fnames)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/addons/hr/models/hr_employee.py", line 170, in _read
    res = self.env['hr.employee.public'].browse(self.ids).read(fields)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/models.py", line 3216, in read
    raise ValueError("Invalid field %r on model %r" % (name, self._name))
Exception
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo_ocb_15_2023-02-05/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'birth_name' on model 'hr.employee.public'

## To Reproduce
Install version 15 of both modules and use it with a standard user without admin rights.

**Expected behavior**
No error message, just Attendance checked in.

**Additional context**
The version I used is already a month old, but I did not see anything in the past which could help (at least not in ODOO 15).

**Comment by Saran440** [comment]
Hi @siarmiel 

Can you show access right that has a problem, please?
I test with this access right but not error
![Selection_028](https://user-images.githubusercontent.com/20896369/222327426-909a6b68-ba0a-43b9-bd4a-20ab53772efd.png)

Install module
- hr_attendance
- hr_employee_birth_name

**Comment by chusamo** [comment]
![hr_attedance](https://github.com/OCA/hr/assets/31690536/c55b6bac-aa11-4708-a58d-96062edde083)
Not being able to reproduce the error.

Demo, has kiosk attedance rule groups.

**Comment by nimarosa** [comment]
Closed, can't reproduce the issue either. Probably your own instance.

**Comment by siarmiel** [comment]
I also cannot reproduce the error anymore. Some third-party modules, which were installed in the particular system probably caused the error. This was not a productive system, just a test installation. Sorry for the inconvenience.
