### ISSUE TITLE
AttributeError: 'hr.applicant' object attribute 'name' is read-only

### ISSUE THREAD

**Issue by 1moere1** [OCA/hr#1255]
## Module
hr_recruitment

## Describe the bug
Trying to create an applicant through the Kanban board of a job results in an error.
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1612, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1810, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 149, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6489, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6200, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/hr_recruitment/models/hr_recruitment.py", line 207, in _onchange_job_id
    applicant.name = applicant.job_id.name
AttributeError: 'hr.applicant' object attribute 'name' is read-only

The above server error caused the following client error:
null
```

## To Reproduce
**Affected versions**: odoo v16, hr_recruitement v16.0.1.1

1. Go to Recruitement
2. Click on the three dots of a job and open Applicants view
3. Click create button

**Expected behavior**
Mask should open to create the applicant with the job already filled out.

**Comment by 1moere1** [comment]
Just tried to create through Applications > All Applicants > New. As soon i choose the Applied Job field, the error appears

**Comment by Saran440** [comment]
@1moere1 Hi,
module `hr_recruitment` is core odoo.
May be you can update your code up-to-date and upgrade module `hr_recruitment` again.
If it still error you can open issue here https://github.com/odoo/odoo/issues
