### ISSUE TITLE
hr_employee_benefit Module Bug when compute benefit button clicked

### ISSUE THREAD

**Issue by newmanx** [OCA/hr#191]
There seems to be a bug with hr_employee_benefit module, After adding the benefit categories and rate, when we click on Benefit compute button under payslips, its returning this error:

OpenERP Server Error
Client Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/openerp/addons/web/http.py", line 204, in dispatch
response["result"] = method(self, _self.params)
File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 1137, in call_button
action = self._call_kw(req, model, method, args, {})
File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 1125, in _call_kw
return getattr(req.session.model(model), method)(args, *_kwargs)
File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 42, in proxy
result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 30, in proxy_method
result = self.session.send(self.service_name, method, *args)
File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 103, in send
raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 89, in send
return openerp.netsvc.dispatch_rpc(service_name, method, args)
File "/usr/lib/python2.7/dist-packages/openerp/netsvc.py", line 306, in dispatch_rpc
result = ExportService.getService(service_name).dispatch(method, params)
File "/usr/lib/python2.7/dist-packages/openerp/service/web_services.py", line 632, in dispatch
res = fn(db, uid, params)
File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 190, in execute_kw
return self.execute(db, uid, obj, method, *args, *kw or {})
File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 132, in wrapper
return f(self, dbname, args, *kwargs)
File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 199, in execute
res = self.execute_cr(cr, uid, obj, method, args, *kw)
File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 187, in execute_cr
return getattr(object, method)(cr, uid, args, *kw)
File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_employee_benefit/models/hr_payslip.py", line 78, in button_compute_benefits
payslip.compute_benefits(payslip)
File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 378, in function_proxy
return attr(self._cr, self._uid, [self._id], args, *kwargs)
TypeError: compute_benefits() got multiple values for keyword argument 'context'

Can you help me to fix this?

**Comment by ghost** [comment]
@newmanx at line 78 of addons/hr_employee_benefit/models/hr_payslip.py

replace this

for payslip in self.browse(cr, uid, ids, context=context):
    payslip.compute_benefits(payslip)

by this

self.compute_benefits(cr, uid, ids, context=context)

**Comment by newmanx** [comment]
@dufresnedavid thanks for your reply,

As soon as i changed, openerp crashed with error "No Handlers Found"
I checked the logs and found this:

2015-11-12 17:11:47,074 2433 ERROR ? openerp.service: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/service/**init**.py", line 60, in load_server_wide_modules
    openerp.modules.module.load_openerp_module(m)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 415, in load_openerp_module
    getattr(sys.modules['openerp.addons.' + module_name], info['post_load'])()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/http.py", line 628, in wsgi_postload
    openerp.wsgi.register_wsgi_handler(Root())
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/http.py", line 517, in **init**
    self.load_addons()
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/http.py", line 580, in load_addons
    m = **import**('openerp.addons.' + module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 133, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_employee_benefit/**init**.py", line 22, in <module>
    from . import models
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_employee_benefit/models/**init**.py", line 27, in <module>
    from . import hr_payslip
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_employee_benefit/models/hr_payslip.py", line 77
    self.compute_benefits(cr, uid, ids, context=context)
       ^
IndentationError: expected an indented block

**Comment by newmanx** [comment]
I removed the module and restored, ERP is now working, can you pls confirm if settings i have made are correct:
1. I created a new Employee Benefit Category called "Provident Fund"
2. Added salary rule "Employer's PF Contribution" to it
3. Created Benefit Rate called "Provident fund" and added to the "Provident fund" benefit category
4. "Employer's PF Contribution" salary rule has following python code for Condition "Always true" 
   result = (payslip.company_id.dearness_allowance and - ((contract.wage + DA) \* 0.12) 
   or - (contract.wage \* 0.12))
5. Added salary rule "Employer's PF Contribution" to Salary structure "Base for new structures"
6. Created a contract called "Antony" for employee "Antony"
7. In the contract for "Antony", pulled "Provident Fund" Employee Benefit Category & "Provident Fund" Benefit Rate, Set start date for last year, no end date, selected Annual pay.
8. Now when i generate the payslip, salary computing happens, but not Benefit contribution, so, i click on "Compute Benefits" and i get the above error.

Please guide me if i am doing the right thing ?

**Comment by newmanx** [comment]
@dufresnedavid, sorry changes you said was not taking place, i re-checked and found, it was reverting to old, i fixed it and it solved the problem.

Thanks a lot, closing the issue.
