### ISSUE TITLE
[hr_wage_increment]: Error when "Individual" Wage Adjustment is clicked

### ISSUE THREAD

**Issue by newmanx** [OCA/hr#195]
I am running openerp 7.0 latest, installed wage_increment along with its dependencies, but when i click on wage adjustment >> Individual, i get below error:

Client Traceback (most recent call last):
File "/usr/lib/pymodules/python2.7/openerp/addons/web/http.py", line 204, in dispatch
response["result"] = method(self, _self.params)
File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1125, in call_kw
return self._call_kw(req, model, method, args, kwargs)
File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1117, in _call_kw
return getattr(req.session.model(model), method)(args, *_kwargs)
File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 42, in proxy
result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 30, in proxy_method
result = self.session.send(self.service_name, method, *args)
File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 103, in send
raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 89, in send
return openerp.netsvc.dispatch_rpc(service_name, method, args)
File "/usr/lib/pymodules/python2.7/openerp/netsvc.py", line 296, in dispatch_rpc
result = ExportService.getService(service_name).dispatch(method, params)
File "/usr/lib/pymodules/python2.7/openerp/service/web_services.py", line 626, in dispatch
res = fn(db, uid, params)
File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 190, in execute_kw
return self.execute(db, uid, obj, method, *args, *kw or {})
File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 132, in wrapper
return f(self, dbname, args, *kwargs)
File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 199, in execute
res = self.execute_cr(cr, uid, obj, method, args, *kw)
File "/usr/lib/pymodules/python2.7/openerp/addons/audittrail/audittrail.py", line 532, in execute_cr
return fct_src(cr, uid, model, method, args, *kw)
File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 187, in execute_cr
return getattr(object, method)(cr, uid, args, *kw)
File "/usr/lib/pymodules/python2.7/openerp/osv/orm.py", line 1599, in default_get
defaults[f] = self._defaultsf
File "/usr/lib/pymodules/python2.7/openerp/addons/hr_wage_increment/wage_increment.py", line 101, in _get_effective_date
contract_id = self._get_contract_id(cr, uid, context=context)
File "/usr/lib/pymodules/python2.7/openerp/addons/hr_wage_increment/wage_increment.py", line 88, in _get_contract_id
data = self._get_contract_data(cr, uid, ['id'], context)
File "/usr/lib/pymodules/python2.7/openerp/addons/hr_wage_increment/wage_increment.py", line 76, in _get_contract_data
cr, uid, employee_id, ['contract_id'], context=context)
File "/usr/lib/pymodules/python2.7/openerp/osv/orm.py", line 3679, in read
result = self._read_flat(cr, user, select, fields, context, load)
File "/usr/lib/pymodules/python2.7/openerp/osv/orm.py", line 3731, in _read_flat
cr.execute(query, [tuple(sub_ids)] + rule_params)
File "/usr/lib/pymodules/python2.7/openerp/sql_db.py", line 161, in wrapper
return f(self, args, *kwargs)
File "/usr/lib/pymodules/python2.7/openerp/sql_db.py", line 226, in execute
res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: integer = boolean
LINE 1: ...ployee.id FROM "hr_employee" WHERE hr_employee.id IN (false)...
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.

**Comment by newmanx** [comment]
I have tried installing hr_employee_legacy_id, hr_employee_id, hr_payroll_extension

still same error, can anyone help me with this bug fix ?

**Comment by ghost** [comment]
@newmanx you should not use hr_payroll_extension. This module is extremely unstable.

**Comment by newmanx** [comment]
@dufresnedavid Thanks for letting me know, but issue remains same without the extension too, what could be this bug ?

**Comment by ghost** [comment]
@newmanx your stack trace does not fit the current version of the module available in OCA. Please take an up to date version.

**Comment by newmanx** [comment]
@dufresnedavid  You are right, I have now updated with OCA version, and when i run its kind of same error. Do you want me to build a new database and install fresh ?

Client Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 1133, in call_kw
    return self._call_kw(req, model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 1125, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/usr/lib/python2.7/dist-packages/openerp/netsvc.py", line 306, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/lib/python2.7/dist-packages/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, _params)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 1614, in default_get
    defaults[f] = self._defaults[f](self, cr, uid, context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 101, in _get_effective_date
    'wage_difference_percent': fields.function(
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 88, in _get_contract_id
    type='float',
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 76, in _get_contract_data
    'hr.contract',
  File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 3707, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 3761, in _read_flat
    cr.execute(query, [tuple(sub_ids)] + rule_params)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: integer = boolean
LINE 1: ...ployee.id FROM "hr_employee" WHERE hr_employee.id IN (false)...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

**Comment by ghost** [comment]
@newmanx yes, you should start with a new db.

**Comment by newmanx** [comment]
@dufresnedavid I updated the entire OCA HR files, rebooted the VM, created a new DB, installed all basic packages like employee directory, payroll, then installed wage_increment, went to create a new change in wage increment, before anything, it returns the same error:

OpenERP Server Error
Client Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 1133, in call_kw
    return self._call_kw(req, model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 1125, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/usr/lib/python2.7/dist-packages/openerp/netsvc.py", line 306, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/lib/python2.7/dist-packages/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, _params)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 1614, in default_get
    defaults[f] = self._defaults[f](self, cr, uid, context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 185, in _get_effective_date
    contract_id = self._get_contract_id(cr, uid, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 172, in _get_contract_id
    data = self._get_contract_data(cr, uid, ['id'], context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 160, in _get_contract_data
    cr, uid, employee_id, ['contract_id'], context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 3707, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 3761, in _read_flat
    cr.execute(query, [tuple(sub_ids)] + rule_params)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: integer = boolean
LINE 1: ...ployee.id FROM "hr_employee" WHERE hr_employee.id IN (false)...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

**Comment by newmanx** [comment]
@dufresnedavid  And  this are from the /var/log/openerp/openerp-server.log

2015-11-19 16:35:02,425 961 ERROR finaltest openerp.sql_db: Programming error: operator does not exist: integer = boolean
LINE 1: ...ployee.id FROM "hr_employee" WHERE hr_employee.id IN (false)...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
, in query SELECT hr_employee."contract_id",hr_employee."resource_id",hr_employee.id FROM "hr_employee" WHERE hr_employee.id IN %s ORDER BY name_related
2015-11-19 16:35:02,426 961 ERROR finaltest openerp.osv.osv: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 1614, in default_get
    defaults[f] = self._defaults[f](self, cr, uid, context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 185, in _get_effective_date
    contract_id = self._get_contract_id(cr, uid, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 172, in _get_contract_id
    data = self._get_contract_data(cr, uid, ['id'], context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 160, in _get_contract_data
    cr, uid, employee_id, ['contract_id'], context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 3707, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 3761, in _read_flat
    cr.execute(query, [tuple(sub_ids)] + rule_params)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: integer = boolean
LINE 1: ...ployee.id FROM "hr_employee" WHERE hr_employee.id IN (false)...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

2015-11-19 16:35:02,426 961 ERROR finaltest openerp.netsvc: operator does not exist: integer = boolean
LINE 1: ...ployee.id FROM "hr_employee" WHERE hr_employee.id IN (false)...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/netsvc.py", line 306, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/lib/python2.7/dist-packages/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, _params)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 1614, in default_get
    defaults[f] = self._defaults[f](self, cr, uid, context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 185, in _get_effective_date
    contract_id = self._get_contract_id(cr, uid, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 172, in _get_contract_id
    data = self._get_contract_data(cr, uid, ['id'], context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/hr_wage_increment/wage_increment.py", line 160, in _get_contract_data
    cr, uid, employee_id, ['contract_id'], context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 3707, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/orm.py", line 3761, in _read_flat
    cr.execute(query, [tuple(sub_ids)] + rule_params)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: integer = boolean
LINE 1: ...ployee.id FROM "hr_employee" WHERE hr_employee.id IN (false)...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

**Comment by ghost** [comment]
@newmanx The module will need unit tests. It is unstable. I understand what causes the problem, but it is not trivial to fix. For now, it would take a couple of hours to sanitise the module. I do not have the time for such developpement, at least, not for free.

**Comment by newmanx** [comment]
@dufresnedavid If you are willing to work on this, let me know how much it will cost? 
Can you give me a quote / estimate ?

thanks

**Comment by ghost** [comment]
@newmanx sure I am willing to work on this. Before making an estimate, I will need more information about you. I need an email address, who you are and the company you work for. You can email those info to me at david.dufresne@savoirfairelinux.

**Comment by newmanx** [comment]
@dufresnedavid  I have sent you a mail with all the details, its from j**_@r**_*****.info
