### ISSUE TITLE
hr_expense_invoice error to install: TypeError: Model 'hr.expense.expense' does not exist in registry.

### ISSUE THREAD

**Issue by allaneramirez** [OCA/hr#395]
Traceback (most recent call last):
  File "/odoodeca/odoodeca-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoodeca/odoodeca-server/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/odoodeca/odoodeca-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoodeca/odoodeca-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoodeca/odoodeca-server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoodeca/odoodeca-server/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/odoodeca/odoodeca-server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoodeca/odoodeca-server/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoodeca/odoodeca-server/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoodeca/odoodeca-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoodeca/odoodeca-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoodeca/odoodeca-server/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoodeca/odoodeca-server/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoodeca/odoodeca-server/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoodeca/odoodeca-server/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/odoodeca/odoodeca-server/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoodeca/odoodeca-server/odoo/modules/loading.py", line 131, in load_module_graph
    model_names = registry.load(cr, package)
  File "/odoodeca/odoodeca-server/odoo/modules/registry.py", line 259, in load
    model = cls._build_model(self, cr)
  File "/odoodeca/odoodeca-server/odoo/models.py", line 531, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'hr.expense.expense' does not exist in registry.

**Comment by pedrobaeza** [comment]
That's what happens when you change the installable = False to force a non migrated module to be in the module list. The migration is here: https://github.com/OCA/hr/pull/367

**Comment by itautomationo** [comment]
Thank you !!!
