### ISSUE TITLE
hr_attendance_report_theoretical_time install error

### ISSUE THREAD

**Issue by joir7** [OCA/hr#599]
Al intentar desplegar el módulo en un odoo 11 nos encontramos con el siguiente error. 

No conseguimos depurar el problema, en principio tenemos todas las dependencias de python al día 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 552, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 153, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/opt/odoo/odoo11/odoo/modules/registry.py", line 307, in init_models
    model.init()
  File "/opt/odoo/odoo11-custom-addons/hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report.py", line 171, in init
    AsIs(self._group_by()),
  File "/opt/odoo/odoo11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
**psycopg2.ProgrammingError: referencia a la entrada de la cláusula FROM para la tabla «he» no válida
LÍNEA 51:                         COALESCE(he.theoretical_hours_start_...
                                           ^
SUGERENCIA:  Hay una entrada para la tabla «he», pero no puede ser referenciada desde esta parte de la consulta.**

**Comment by etobella** [comment]
Please, speak in english as most users do not speak spanish.

Which version of Postgres are you using? We had the same issue on travis until we set postgres 9.6

**Comment by joir7** [comment]
Excuse the language :) 

The current database is 9.2.4. I will try to update to 9.6

**Comment by etobella** [comment]
@joir7 Has this been solved?

**Comment by joir7** [comment]
Hi, Eric 

Forgives that he did not update the ticket.  

Yesterday update to version 9.6 of PostgreSQL and as you said the problem has been solved.  

Thanks for the help and forgive again
