### ISSUE TITLE
[12.0][BUG][hr_skill] Employees cannot access to their information

### ISSUE THREAD

**Issue by rafaelbn** [OCA/hr#626]
This module hr_skill makes that all the employees lose access to their employee form as hr.employee.skill must have Employees/officer permission.

- It should allow to access but hide the Skills tab

![2019-06-20_1-50-02](https://user-images.githubusercontent.com/8736623/59808851-40526180-92fe-11e9-97e7-e2015f71dc8e.png)

Note: because this issue we cannot test some other modules in this repo. When I uninstall this module hr_skill and I try to access to the employee I get:

Error:
Uncaught TypeError: Cannot read property 'string' of undefined

http://3375425-12-0-e3fa0a.runbot1.odoo-community.org/web/content/599-6e458e7/web.assets_backend.js:1640
Traceback:
TypeError: Cannot read property 'string' of undefined
    at Class._renderTagLabel (http://3375425-12-0-e3fa0a.runbot1.odoo-community.org/web/content/599-6e458e7/web.assets_backend.js:1640:660)
    at Class._renderInnerGroupLabel (http://3375425-12-0-e3fa0a.runbot1.odoo-community.org/web/content/599-6e458e7/web.assets_backend.js:1631:105)
    at http://3375425-12-0-e3fa0a.runbot1.odoo-community.org/web/content/599-6e458e7/web.assets_backend.js:1628:114
    at Function._.each._.forEach (http://3375425-12-0-e3fa0a.runbot1.odoo-community.org/web/content/579-5827a65/web.assets_common.js:12:558)
    at Class._renderInnerGroup (http://3375425-12-0-e3fa0a.runbot1.odoo-community.org/web/content/599-6e458e7/web.assets_backend.js:1625:63)
    at Class._renderTagGroup (http://3375425-12-0-e3fa0a.runbot1.odoo-community.org/web/content/599-6e458e7/web.assets_backend.js:1639:228)
    at Class._renderNode [as _super] (http://3375425-12-0-e3fa0a.runbot1.odoo-community.org/web/content/599-6e458e7/web.assets_backend.js:1631:246)
    at Class._renderNode (http://3375425-12-0-e3fa0a.runbot1.odoo-community.org/web/content/599-6e458e7/web.assets_backend.js:2890:50)
    at Class._renderNode (http://3375425-12-0-e3fa0a.runbot1.odoo-community.org/web/content/579-5827a65/web.assets_common.js:3541:371)
    at http://3375425-12-0-e3fa0a.runbot1.odoo-community.org/web/content/599-6e458e7/web.assets_backend.js:1636:17

**Comment by alexey-pelykh** [comment]
@rafaelbn yep, here's the issue:
```
"access_employee_skill_user","hr.employee.skill","model_hr_employee_skill","hr.group_hr_user",1,1,1,1
```
How do we want this - skills of the employee to be visible only by HR, by all, or by HR-and-myself?

**Comment by max3903** [comment]
@alexey-pelykh I would say by all. There is nothing confidential about this...

**Comment by alexey-pelykh** [comment]
@max3903 @rafaelbn please check https://github.com/OCA/hr/pull/633

**Comment by rafaelbn** [comment]
Thanks @alexey-pelykh . Fixed
