### ISSUE TITLE
[11.0] Error Updating hr_holidays_compute_days -  11.0.1.0.0 to 11.0.1.2.0 

### ISSUE THREAD

**Issue by altoch** [OCA/hr#647]
When trying to update the module it throws this error, related to open AttributeError: module 'openupgradelib.openupgrade' has no attribute 'delete_records_safely_by_xml_id'

pip3 show openupgradelib
Name: openupgradelib
Version: 2.0.0
Summary: A library with support functions to be called from Odoo migration scripts.
Home-page: https://github.com/OCA/openupgradelib
Author: Odoo Community Association (OCA)

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-51>", line 2, in button_immediate_upgrade
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 613, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 552, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 135, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/opt/odoo/odoo11/odoo/modules/migration.py", line 190, in migrate_module
    migrate(self.cr, installed_version)
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/odoo11-custom-addons/hr_holidays_compute_days/migrations/11.0.1.2.0/pre-migrate.py", line 9, in migrate
    openupgrade.delete_records_safely_by_xml_id(
AttributeError: module 'openupgradelib.openupgrade' has no attribute 'delete_records_safely_by_xml_id'
```

**Comment by pedrobaeza** [comment]
Install openupgradelib from source, not from pypi

**Comment by altoch** [comment]
As always a clear and a good solution. It worked flawlessly.
If any doesn't know how to install from source openupgradelib, here my steps.
Uninstall any old version from openupgradelib installed.

· Clone from git openupgradelib
git clone  https://github.com/OCA/openupgradelib
· If you want to install it inside your virtual environment for odoo, activate it
source bin/activate
· Enter in openupgradelib repo
cd openupgradelib
· Install
 python3 setup.py install --single-version-externally-managed --root=/
·Reboot your server

**Comment by pedrobaeza** [comment]
Or you can do:
```
pip3 install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master
```
