### ISSUE TITLE
[12.0] Payroll, Global Leaves

### ISSUE THREAD

**Issue by Slivi-sliv** [OCA/hr#781]
I have a problem:
I've added all the holidays to the Working Times / Global Leaves section.
Let's say:
25.12.2019 is the holiday (Christmas). One of the employees has sick leave from 1.12.2019 to 31.12.2019.
However, when I try to create Payroll for 1.12.2019 to 31.12.2019, I get an error.
However, if I delete the holiday, then everything is fine.
Is there any solution to this?

**Comment by Slivi-sliv** [comment]
I get the following error:

`
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4721, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5510, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5354, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/hr_payroll/models/hr_payslip.py", line 480, in onchange_employee
    worked_days_line_ids = self.get_worked_day_lines(contracts, date_from, date_to)
  File "/usr/lib/python3/dist-packages/odoo/addons/hr_payroll/models/hr_payslip.py", line 192, in get_worked_day_lines
    holiday = leave.holiday_id
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 987, in __get__
    record.ensure_one()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4724, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: resource.calendar.leaves(76, 150)
`

**Comment by alexey-pelykh** [comment]
Please try to reproduce in on a OCA runbot, if that's reproducible there and caused by OCA module, we'll definitely take a look eventually
