### ISSUE TITLE
hr_period: date_range.py error when create period

### ISSUE THREAD

**Issue by Dariuzcm** [OCA/hr#882]
I'd an error when I tried to create a period,, it happend becouse when date_from or date_end are changed  try to assign hr.period object into an date.range object , on next the images, also happends into hr_fiscalyear by the way.

![Captura de pantalla de 2020-09-04 12-51-06](https://user-images.githubusercontent.com/28762220/92271479-7b15ca80-eead-11ea-9ec3-0f1b5369b9b8.png)
![Captura de pantalla de 2020-09-04 12-51-44](https://user-images.githubusercontent.com/28762220/92271486-7fda7e80-eead-11ea-9e8d-a13decb0fca0.png)

Error here:
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-10.0/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-10.0/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/models.py", line 5555, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/.repo_requirements/odoo/odoo/models.py", line 5453, in _onchange_eval
    method_res = method(self)
  File "/home/odoo/dependencies/server-tools/date_range/models/date_range.py", line 167, in onchange_type_id
    self.parent_id = possible_parent  # can be empty!
  File "/.repo_requirements/odoo/odoo/fields.py", line 949, in __set__
    value = self.convert_to_cache(value, record)
  File "/.repo_requirements/odoo/odoo/fields.py", line 1973, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for hr.period.parent_id: hr.period()

**Comment by AaronHForgeFlow** [comment]
Hi, this was because the hierarchy in date ranges was added later hr_period was merged. I proposed first to disable the onchange more than a year ago (https://github.com/OCA/hr/pull/575), but the solution proposed is fine to me as well.

**Comment by AaronHForgeFlow** [comment]
This is already fixed. Please confirm @Dariuzcm .

**Comment by AaronHForgeFlow** [comment]
Can we close this?

**Comment by Saran440** [comment]
done with https://github.com/OCA/hr/pull/883
